### ISSUE TITLE
Installation error TypeError: api.assertCliVersion is not a function

### ISSUE THREAD

**Issue by network-rail** [storybookjs/vue-cli-plugin-storybook#101]
I've just tried to install it in a fresh Vue cli project and I've got the error:

```
TypeError: api.assertCliVersion is not a function
    at module.exports (/Users/carlos/Sites/vue-cli-standard-installation/node_modules/vue-cli-plugin-storybook/generator/index.js:5:7)
    at /Users/carlos/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:103:7
    at Array.forEach (<anonymous>)
    at new Generator (/Users/carlos/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:101:13)
    at runGenerator (/Users/carlos/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:123:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async invoke (/Users/carlos/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:117:3)
```
### To Reproduce
1. vue create your-project (default)
2. vue add storybook (default)

vue-vli 3.8.2
node v13.8.0
yarn 1.19.1

**Comment by pksunkara** [comment]
You need a newer vue-cli version. Try v4.
