### ISSUE TITLE
Failed to install on a new project usingg vue ui in windows

### ISSUE THREAD

**Issue by blowsie** [storybookjs/vue-cli-plugin-storybook#106]
```
The filename, directory name, or volume label syntax is incorrect.
{ Error: Command failed: vue invoke vue-cli-plugin-storybook --$inlineOptions {"type":"init","semver":">=5.3.0","csf":true,"docs":true}

    at makeError (C:\Users\sblowes\AppData\Roaming\nvm\v10.16.3\node_modules\@vue\cli\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\sblowes\AppData\Roaming\nvm\v10.16.3\node_modules\@vue\cli\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'vue invoke vue-cli-plugin-storybook --$inlineOptions {"type":"init","semver":">=5.3.0","csf":true,"docs":true}',
  timedOut: false,
  killed: false }


```

**Comment by pksunkara** [comment]
What's the `@vue/cli` version you are using?

**Comment by blowsie** [comment]
````λ vue --version
@vue/cli 4.5.2
```
