### ISSUE TITLE
[Bug] Storybook 7 Vue migration: Cannot find module '@storybook/core/server'

### ISSUE THREAD

**Issue by marcoarruda** [storybookjs/vue-cli-plugin-storybook#132]
### Describe the bug

After running the migration cli wizard `npx sb upgrade`

### Steps to reproduce the behavior

1. Go to your project root folder (that runs storybook 6.5)
2. Run the migration commend `npx sb upgrade`
3. Answer the questions accordingly to your project
4. Run the serve and see the error

`Error: Cannot find module '@storybook/core/server'`

### Expected behavior

To run the server properly

### Screenshots and/or logs

I found a similar issue and a PR to fix the same (or very close to) issue for version 6.5
https://github.com/storybookjs/vue-cli-plugin-storybook/issues/128

### Environment

 - OS: ARM M1 silicon
 - Node.js version: v16.17.1
 - NPM version: 8.15.0

### Additional context

https://github.com/storybookjs/vue-cli-plugin-storybook/issues/128

**Comment by IanVS** [comment]
Can you please start over and try running `npx sb@latest upgrade`?  npx is notorious for using cached versions, which can cause lots of problems for Storybook.

**Comment by sybers** [comment]
I also tried to migrate using Storybook's auto migration tool and encountered this issue:

```
➜ yarn storybook
yarn run v1.22.19
$ vue-cli-service storybook:serve -p 6006 -c config/storybook
 ERROR  TypeError: server.buildDev is not a function
TypeError: server.buildDev is not a function
    at /Users/xxx/Workspace/xxx/node_modules/vue-cli-plugin-storybook/lib/index.js:42:12
    at Service.run (/Users/xxx/Workspace/xxx/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by IanVS** [comment]
@sybers that sounds like a different issue.  Could you please open a new issue (ideally with a reproduction), and mention me on it so I see it?

But if I had to guess, I'd say `vue-cli-plugin-storybook` might not be compatible with 7.0.  I would start there by checking that.

**Comment by IanVS** [comment]
doh, I didn't realize this _was_ the repo for the plugin.  😵
