### ISSUE TITLE
vue add storybook command gives Error: EPERM

### ISSUE THREAD

**Issue by MatthijsBe** [storybookjs/vue-cli-plugin-storybook#94]
Hi everyone, 

I'm trying to add `vue add storybook` so I can use Storybook Docs and MDX.

When running the command:

✔  Successfully installed plugin: vue-cli-plugin-storybook

so far so good, now it's time for some options:

```
? What do you want to generate? Initial framework
? What storybook version do you want? (Please specify semver range) 5.3.14
? Use Storybook CSF (component story format)? Yes
? Use Storybook Docs? Yes
```
And then:

```
�  Invoking generator for vue-cli-plugin-storybook...
 ERROR  Error: EPERM: operation not permitted, open 'C:\Projects\Vue\configurable-prototype-clientapp\.svn\pristine\00\00108274072869f6003cd1cb732feddebbbe1a76.svn-base'
Error: EPERM: operation not permitted, open 'C:\Projects\Vue\configurable-prototype-clientapp\.svn\pristine\00\00108274072869f6003cd1cb732feddebbbe1a76.svn-base'
    at Object.openSync (fs.js:457:3)
    at Object.writeFileSync (fs.js:1282:35)
    at C:\Users\Developer\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\writeFileTree.js:25:8
    at Array.forEach (<anonymous>)
    at writeFileTree (C:\Users\Developer\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\writeFileTree.js:22:22)
    at async Generator.generate (C:\Users\Developer\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:180:5)
    at async runGenerator (C:\Users\Developer\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:109:3)
    at async invoke (C:\Users\Developer\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:90:3)
C:\Projects\Vue\configurable-prototype-clientapp
```

Somehow it wants to look inside my .svn folder, is there any work around? or possible fix?

I've tried, npm cache clean, removed node_modules and reinstall no success so far.

What am I using?
Node version: 12.16.0
Npm version: 6.14.2
Yarn version: 1.22.0
Vue version : @vue/cli 4.2.3
Storybook version: 5.314

**Comment by pksunkara** [comment]
I think it might be a vue-cli issue. Can you install other plugins?

**Comment by MatthijsBe** [comment]
@pksunkara Hmm I think you're right tried with `vue add apollo` this will give the same error.

I will try another vue cli version, thanks in advance :)
